### ISSUE TITLE
Net::SMTPError types interface changed in a patch release 0.2.2

### ISSUE THREAD

**Issue by jrafanie** [ruby/net-smtp#48]
Hello!

I wanted to share that pull request #26 changed the interface of all Net::SMTPError error types in a patch release.  I'm unsure if this was intentional or not.

The interface changed from:
* accepting an optional message argument like nearly all ruby exceptions

To:
* requiring a response object and an optional message kwarg

This makes it impossible to `raise Net::SMTPError` or to mock it in tests without adding a response or fake response object.  A ruby developer would likely not expect this interface change.

This released in 0.2.2 and is not listed as an incompatibility in the news:
https://github.com/ruby/net-smtp/blob/master/NEWS.md#version-022-2021-10-09

I can open a PR to add an incompatibility line but wanted to make you aware of this as it doesn't follow semantic versioning.

I see another issue ran into this:
https://github.com/rails/rails/issues/44105

We noticed this in our tests when the mail gem was upgraded to 2.8.0 and began requiring the standalone net-smtp gem: 
https://github.com/ManageIQ/manageiq/pull/22268

**Comment by hsbt** [comment]
Basically, We didn't follow semver policy.

**Comment by hsbt** [comment]
@jrafanie Unfortunately, there is no action for this. I'll close this.
